### ISSUE TITLE
Issue while running in azure function

### ISSUE THREAD

**Issue by aosyatnik** [Tazmainiandevil/TableStorage.Abstractions#13] opened 2020-11-06 13:01 UTC
Hi, thank you for this great library!
I used it in azure function, but unfortunately, there is an issue. Something connected with `CreateIfNotExists`. Looks like this (from function log):
![image](https://user-images.githubusercontent.com/8158404/98368691-0b9c9280-2038-11eb-84d7-b9b3d1ed8df2.png)

I could resolve my issue by calling `CreateIfNotExistsAsync` manually. Like this:
```c#
public const string CUSTOMERS_TABLE_NAME = "Customers";

private readonly ILogger _logger;
private readonly ITableStore<CustomerEntity> _customersTable;

public CustomerService(ILogger<ICustomerService> logger, IOptions<SystemStorageOptions> options, ITableStoreFactory factory)
        {
            _logger = logger;
            _customersTable = factory.CreateTableStore<CustomerEntity>(CUSTOMERS_TABLE_NAME, options.Value.ConnectionString, new TableStorageOptions() { EnsureTableExists = false });
        }

private async Task EnsureTableExists()
        {
            if (!await _customersTable.TableExistsAsync())
                await _customersTable.CreateTableAsync();
        }
```

But it would be great if you can check it and fix :) I used these packages in azure function:
```xml
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.14.0" />
<PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.8" />
```

**Comment by Tazmainiandevil** [comment] 2020-11-06 18:36
Hi,

I hadn't ran the code in an Azure Function previously so thanks for the feedback. I'll try running it and see if I can recreate your problem.

Thanks

**Comment by Tazmainiandevil** [comment] 2020-11-07 10:17
It looks like there is a change with CreateIfNotExists between Microsoft.Azure.Cosmos.Table 1.0.7 which the code was using and Microsoft.Azure.Cosmos.Table 1.0.8 which you had added. When you run with both loaded the exception is thrown.
I've updated the code to use 1.0.8 and there is a new nuget package.

Hopefully that resolves the issue for you.

**Comment by aosyatnik** [comment] 2020-11-09 09:52
Hi, @Tazmainiandevil , thank you for the update. Looks like it should work. But there is an exception in `GetAllRecordsAsync`. Looks like it's not checking if the table exists:
![image](https://user-images.githubusercontent.com/8158404/98526042-96b89b00-2279-11eb-818e-f13b2cc3dba6.png)

**Comment by Tazmainiandevil** [comment] 2020-11-29 15:30
That is by design. Checking if the table exists is an expensive call and that is why the check is done at construction.

I will close this issue as I expect the original issue is now resolved.

**Closed as completed by Tazmainiandevil** 2020-11-29 15:30 UTC
